---
- name: Requre privilege escalation
  hosts: serverb.lab.example.com
  become: yes

  tasks:
    - name: ensure latest packages are installed
      yum:
        name: 
          - firewalld
          - httpd
          - php
          - php-mysql
          - mariadb-server
        state: latest

    - name: ensure firewalld service is enabled and started
      service:
        name: firewalld
        enabled: true
        state: started

    - name: firewalld permits http service
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    - name: httpd service is enabled and started
      service: 
        name: httpd
        enabled: true
        state: started
    
    - name: mariadb server is enabled and started
      service: 
        name: mariadb
        enabled: true
        state: started

    - name: test html page is installed
      get_url: 
        url: http://materials.example.com/grading/var/www/html/index.php
        dest: /var/www/html/index.php

- name: confirm url returns 200
  hosts: localhost
  tasks:
    - name: confirmation
      uri:
        url: http://serverb.lab.example.com
        status_code: 200
